### ISSUE TITLE
Variable policy_estimator error at the begin of task 3

### ISSUE THREAD

**Issue by yhgon** [xujinfan/Reinforced-Continual-Learning#1]
Dear @xujinfan 

thanks for your sharing the great work.

When I try to reproduce your result, I found at the start point of RCL.py#L89 in Task_id=3, have error as below.
 ```
ValueError: Variable policy_estimator/LSTM/multi_rnn_cell/cell_0/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py", line 38, in __init__
    (cell_output, hidden_state) = cell(inputs, hidden_state)
```
detail log are below. I just add print for debugging purpose.  https://github.com/yhgon/Reinforced-Continual-Learning/blob/master/RCL.py 
```
task 0/4  epoch 3  train_step 54272/55000
task 0/4  epoch 3  train_step 54784/55000
task 0/4  epoch 3  train_step 55296/55000
task 0/4 test accuracy: 0.9463000297546387 IF
DEBUG : task 1/4 ELSE
WARNING:tensorflow:From /mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py:32: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
WARNING:tensorflow:From /mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py:51: get_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_global_step
DEBUG : taks1/4 ELSE finish Controller 
DEBUG : taks1/4 ELSE result Controller 
DEBUG : taks1/4 ELSE start trial loop 
task 1/4 trial 0/2 *********actions  for [2, 18] ELSE 
task:1, epoch 0/4  55296/55000 test accuracy:0.15389999747276306 for evaluate action
task:1, epoch 3/4  55296/55000 test accuracy:0.5547999739646912 for evaluate action
task 1/4  trial 0/2, test accuracy: 0.5547999739646912 ELSE
                              reward: 0.5562000017166138 ELSE
DEBUG : task 1/4 trial 0/2 ELSE done best_reward 
DEBUG : task 1/4 trial 0/2 ELSE end trial internal loop for train_control 
task 1/4 trial 1/2 *********actions  for [3, 0] ELSE 
task:1, epoch 0/4  55296/55000 test accuracy:0.1509000062942505 for evaluate action
task:1, epoch 3/4  55296/55000 test accuracy:0.6255000233650208 for evaluate action
task 1/4  trial 1/2, test accuracy: 0.6255000233650208 ELSE
                              reward: 0.6373000046730042 ELSE
DEBUG : task 1/4 trial 1/2 ELSE done best_reward 
DEBUG : task 1/4 trial 1/2 ELSE end trial internal loop for train_control 
DEBUG : task 1/4 ELSE end trial loop 
DEBUG : task 1/4 ELSE end controller session 
DEBUG : task 1/4 ELSE end result append 
DEBUG : task 1/4 ELSE end self vars 
DEBUG : task 1/4 ELSE end loop 

DEBUG : task 2/4 ELSE start
Traceback (most recent call last):

Traceback (most recent call last):
  File "RCL.py", line 170, in <module>
    jason = RCL(args)
  File "RCL.py", line 32, in __init__
    self.train()
  File "RCL.py", line 93, in train
    controller = Controller(self.args)
  File "/mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py", line 104, in __init__
    self.policy_estimator = PolicyEstimator(args)
  File "/mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py", line 38, in __init__
    (cell_output, hidden_state) = cell(inputs, hidden_state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 233, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1486, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 370, in __call__
    *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 746, in __call__
    self.build(input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/tf_utils.py", line 149, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 716, in build
    shape=[input_depth + h_depth, 4 * self._num_units])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 495, in add_variable
    return self.add_weight(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 288, in add_weight
    getter=vs.get_variable)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 609, in add_weight
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpointable/base.py", line 639, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 523, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 236, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 861, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable policy_estimator/LSTM/multi_rnn_cell/cell_0/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py", line 38, in __init__
    (cell_output, hidden_state) = cell(inputs, hidden_state)
  File "/mnt/dataset/lsun/Reinforced-Continual-Learning/policy_gradient.py", line 104, in __init__
    self.policy_estimator = PolicyEstimator(args)
  File "RCL.py", line 93, in train
    controller = Controller(self.args)

```

**Comment by yhgon** [comment]
I found temporal solution.

it works after adding  *`tf.reset_default_graph()`* before start task as below, : 
https://github.com/yhgon/Reinforced-Continual-Learning/blob/master/RCL.py#L96

eliminate *`controller.close_session()`* after train
https://github.com/yhgon/Reinforced-Continual-Learning/blob/master/RCL.py#L123

Training work well but I'm wonder these temporal solution would affect any side effect for *search  state space*.  
Could you verify my temporal solution?
```
python RCL.py --batch_size 512 --n_epochs 30  --n_tasks 10 --n_layers 4 --num_layers 4  --max_trials 50

```

**Comment by xujinfan** [comment]
Thank you for your valuable advice. My codes used to be wrote by pytorch, there may be some mistakes when I transfer my codes to tensorflow. I have revised the codes based on you suggestions. Thank you again.

Sincerely,
Ju Xu

**Comment by yhgon** [comment]
Do you have any plan to share your pytorch baseline? I love to see  pytorch script. 

I'll share my output lot. my result below 
 
RCL_FC_mnist_permutations.pkl_2019-02-06_12:47:53_0.001_30_50_512_critic_0.0001_adam_30_5472.106951951981_policy.txt
```
[(784, 312), (312,), (312, 128), (128,), (128, 10), (10,)]
[(784, 339), (339,), (339, 128), (128,), (128, 10), (10,)]
[(784, 362), (362,), (362, 130), (130,), (130, 10), (10,)]
[(784, 391), (391,), (391, 148), (148,), (148, 10), (10,)]
[(784, 420), (420,), (420, 154), (154,), (154, 10), (10,)]
[(784, 448), (448,), (448, 157), (157,), (157, 10), (10,)]
[(784, 476), (476,), (476, 159), (159,), (159, 10), (10,)]
[(784, 505), (505,), (505, 161), (161,), (161, 10), (10,)]
[(784, 533), (533,), (533, 174), (174,), (174, 10), (10,)]
[(784, 561), (561,), (561, 182), (182,), (182, 10), (10,)]
[0.9782, 0.9618, 0.9605, 0.9612, 0.9606, 0.9585, 0.9651, 0.9638, 0.9642, 0.9618]
```
I'll also share my second try
python RCL.py --batch_size 64 --n_epochs 60  --n_tasks 10 --n_layers 2 --num_layers 2  --max_trials 50

**Comment by xujinfan** [comment]
This is one of my results from the codes of tensorflow."RCL_FC_mnist_permutations.pkl_2019-02-07_01:56:21_0.001_15_50_32_critic_0.0001_adam_30_12996.646098136902_policy.txt" 11L, 670C                                                          1,1           All [(784, 312), (312,), (312, 128), (128,), (128, 10), (10,)] [(784, 338), (338,), (338, 139), (139,), (139, 10), (10,)] [(784, 356), (356,), (356, 141), (141,), (141, 10), (10,)] [(784, 381), (381,), (381, 141), (141,), (141, 10), (10,)] [(784, 403), (403,), (403, 160), (160,), (160, 10), (10,)] [(784, 432), (432,), (432, 179), (179,), (179, 10), (10,)] [(784, 457), (457,), (457, 184), (184,), (184, 10), (10,)] [(784, 478), (478,), (478, 184), (184,), (184, 10), (10,)] [(784, 501), (501,), (501, 191), (191,), (191, 10), (10,)] [(784, 527), (527,), (527, 191), (191,), (191, 10), (10,)] [0.9785, 0.9663, 0.9606, 0.9678, 0.9668, 0.9665, 0.966, 0.9645, 0.9631, 0.9663]The average accuracy is 0.9666. You can obtain this result by using the default setting, not with your large batch size, your large number of epochs.On Feb 6, 2019, at 9:24 PM, Hyungon_Ryu <notifications@github.com> wrote:Do you have any plan to share your pytorch baseline? I love to see  pytorch script.I'll share my output lot. my result belowRCL_FC_mnist_permutations.pkl_2019-02-06_12:47:53_0.001_30_50_512_critic_0.0001_adam_30_5472.106951951981_policy.txt
[(784, 312), (312,), (312, 128), (128,), (128, 10), (10,)]
[(784, 339), (339,), (339, 128), (128,), (128, 10), (10,)]
[(784, 362), (362,), (362, 130), (130,), (130, 10), (10,)]
[(784, 391), (391,), (391, 148), (148,), (148, 10), (10,)]
[(784, 420), (420,), (420, 154), (154,), (154, 10), (10,)]
[(784, 448), (448,), (448, 157), (157,), (157, 10), (10,)]
[(784, 476), (476,), (476, 159), (159,), (159, 10), (10,)]
[(784, 505), (505,), (505, 161), (161,), (161, 10), (10,)]
[(784, 533), (533,), (533, 174), (174,), (174, 10), (10,)]
[(784, 561), (561,), (561, 182), (182,), (182, 10), (10,)]
[0.9782, 0.9618, 0.9605, 0.9612, 0.9606, 0.9585, 0.9651, 0.9638, 0.9642, 0.9618]
I'll also share my second try
python RCL.py --batch_size 64 --n_epochs 60  --n_tasks 10 --n_layers 2 --num_layers 2  --max_trials 50—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yhgon** [comment]
good result which I expected with small batch size. 
  
```
python RCL.py --batch_size 64 --n_epochs 60  --n_tasks 10 --n_layers 2 --num_layers 2  --max_trials 40 
[(784, 312), (312,), (312, 128), (128,), (128, 10), (10,)]
[(784, 334), (334,), (334, 132), (132,), (132, 10), (10,)]
[(784, 357), (357,), (357, 156), (156,), (156, 10), (10,)]
[(784, 386), (386,), (386, 181), (181,), (181, 10), (10,)]
[(784, 408), (408,), (408, 181), (181,), (181, 10), (10,)]
[(784, 435), (435,), (435, 199), (199,), (199, 10), (10,)]
[(784, 456), (456,), (456, 205), (205,), (205, 10), (10,)]
[(784, 485), (485,), (485, 214), (214,), (214, 10), (10,)]
[(784, 513), (513,), (513, 234), (234,), (234, 10), (10,)]
[(784, 536), (536,), (536, 242), (242,), (242, 10), (10,)]
[0.979, 0.9679, 0.9682, 0.9712, 0.9712, 0.9701, 0.9685, 0.9739, 0.9729, 0.9708]
```
I'll try next run to reproduce your MNIST result 
`python RCL.py --batch_size 32 --n_epochs 15  --n_tasks 10 --n_layers 2 --hidden_size 100  --num_layers 2  --max_trials 30
`

**Comment by yhgon** [comment]
log for `python RCL.py --batch_size 32 --n_epochs 15  --n_tasks 10 --n_layers 2 --hidden_size 100  --num_layers 2  --max_trials 30`

```
cat RCL_FC_mnist_permutations.pkl_2019-02-07_15:34:30_0.001_15_30_32_critic_0.0001_adam_30_10035.745239257812_policy.txt
[(784, 312), (312,), (312, 128), (128,), (128, 10), (10,)]
[(784, 337), (337,), (337, 128), (128,), (128, 10), (10,)]
[(784, 357), (357,), (357, 138), (138,), (138, 10), (10,)]
[(784, 374), (374,), (374, 144), (144,), (144, 10), (10,)]
[(784, 403), (403,), (403, 148), (148,), (148, 10), (10,)]
[(784, 432), (432,), (432, 174), (174,), (174, 10), (10,)]
[(784, 454), (454,), (454, 184), (184,), (184, 10), (10,)]
[(784, 479), (479,), (479, 194), (194,), (194, 10), (10,)]
[(784, 498), (498,), (498, 194), (194,), (194, 10), (10,)]
[(784, 519), (519,), (519, 199), (199,), (199, 10), (10,)]
[0.9782, 0.9666, 0.9665, 0.9619, 0.9692, 0.9668, 0.9641, 0.9694, 0.9644, 0.9654]
```
